name: Test Job

on:
  push:

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello 1
        run: |
          echo "Hello 1"
        shell: bash

      - name: sleep 10 seconds
        run: |
          sleep 10
        shell: bash

      - name: Hello 2
        run: |
          echo "Hello 2"
        shell: bash
