name: Test-Job-2

on:
  workflow_dispatch:

concurrency:
  group: test_job_2
  cancel-in-progress: false

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello 1
        run: |
          echo "Hello 1"
        shell: bash

      - name: sleep 30 seconds
        run: |
          sleep 30
        shell: bash

      - name: Hello 2
        run: |
          echo "Hello 2"
        shell: bash
